default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: reservation_development
  pool: 5
  username: reservation
  password: reservation

test:
  adapter: postgresql
  encoding: unicode
  database: reservation_test
  pool: 5
  username: reservation
  password: reservation